In [3]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

In [10]:
Y0=[0,1,1,1] #arreglo con las condiciones iniciales 
t=np.linspace(0,10,10000) #tiempo que dura la vaina

l=1 #Parámetro lambda 

def f(Y,t):
    x,y,px,py=Y 
    
    dx= px
    dpx=-x-2*l*x*y
    dy=py
    dpy=-y-l*(x**2-y**2)
    
    
    return ([dx,dpx,dy,dpy])

sol=odeint(f,Y0,t)

print (sol)


[[0.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00060011e-03 9.99998499e-01 1.00100010e+00 9.99999998e-01]
 [2.00220042e-03 9.99993994e-01 1.00200020e+00 9.99999992e-01]
 ...
 [6.13461346e+00 6.13561356e+00 6.13661366e+00 6.13761376e+00]
 [6.13861386e+00 6.13961396e+00 6.14061406e+00 6.14161416e+00]
 [6.14261426e+00 6.14361436e+00 6.14461446e+00 6.14561456e+00]]
